// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARgSMLlzTf6mAm0Zl93lLxeOzjsRsG6Zs',
    appId: '1:440899426284:web:9e7a232f5646d93ff492c9',
    messagingSenderId: '440899426284',
    projectId: 'kumit-4cd27',
    authDomain: 'kumit-4cd27.firebaseapp.com',
    databaseURL: 'https://kumit-4cd27-default-rtdb.firebaseio.com',
    storageBucket: 'kumit-4cd27.appspot.com',
    measurementId: 'G-PWX6S8GYM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiBiV1wggCX0gG2Un_TS4FNZjXYDLkRik',
    appId: '1:440899426284:android:4ea3d92e52211efaf492c9',
    messagingSenderId: '440899426284',
    projectId: 'kumit-4cd27',
    databaseURL: 'https://kumit-4cd27-default-rtdb.firebaseio.com',
    storageBucket: 'kumit-4cd27.appspot.com',
  );
}
